apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wkvm8cz37-python-gitops
  description: This is GitOps manifest for wkvm8cz37-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=wkvm8cz37-python
    backstage.io/kubernetes-id: wkvm8cz37-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: wkvm8cz37-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wkvm8cz37-python
