apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wkvm8cz37-python
  janus-idp.io/tekton: wkvm8cz37-python
  backstage.io/kubernetes-id: wkvm8cz37-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wkvm8cz37-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
